### ISSUE TITLE
FullInspector breaks Polybrush asset

### ISSUE THREAD

**Issue by Disastercake** [jacobdufault/fullinspector#162] opened 2016-07-26 04:58 UTC
Polybrush: https://www.assetstore.unity3d.com/en/#!/content/53662

By having FullInspector installed in the same project as Polybrush, it causes Polybrush's paint tab to throw an error and fail to load the window, forcing the user to revert to factory settings to close the window.

The error:
`InvalidCastException: Cannot cast from source type to destination type.
Polybrush.z_BrushModePaint.get_colorPaletteEditor () (at Assets/ProCore/Polybrush/Code/Editor/Brush Modes/z_BrushModePaint.cs:72)
Polybrush.z_BrushModePaint.DrawGUI (Polybrush.z_BrushSettings brushSettings) (at Assets/ProCore/Polybrush/Code/Editor/Brush Modes/z_BrushModePaint.cs:132)
Polybrush.z_Editor.OnGUI () (at Assets/ProCore/Polybrush/Code/Editor/Interface/z_Editor.cs:307)
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:222)`

I have sent you a reproing project to your support e-mail that was found on this page: https://www.assetstore.unity3d.com/en/#!/content/14913

**Comment by karl-** [comment] 2016-07-26 13:43
To provide a little more context, here is the absolute simplest reproduce-able case.  3 files, `TestObject.cs`, `TestWindow.cs`, and `TestEditor.cs`.  

To reproduce, open `Window/Test Create Editor Window` with Full Inspector installed.  If you remove `Full Inspector` the editor window behaves as expected.

```
using UnityEngine;
using UnityEditor;
using System.Collections;

namespace TestNamespace
{
	public class TestWindow : EditorWindow
	{
		[SerializeField] private TestEditor testEditor;
		[SerializeField] TestObject testObject;

		[MenuItem("Window/Test Create Editor Window")]
		static void Init()
		{
			EditorWindow.GetWindow<TestWindow>().Show();
		}

		void OnEnable()
		{
			testObject = ScriptableObject.CreateInstance<TestObject>();

			testEditor = (TestEditor) Editor.CreateEditor(testObject);
		}

		void OnGUI()
		{
			// a null check is added here so that Unity doesn't lock up when
			// testEditor doesn't get initialized due to "InvalidCastException"

			if(testEditor != null)
				testEditor.OnInspectorGUI();
		}
	}
}
```

```
using UnityEngine;
using UnityEditor;
using System.Collections;

namespace TestNamespace
{
	[CustomEditor(typeof(TestObject), isFallback = true)]
	public class TestEditor : Editor
	{
		public override void OnInspectorGUI()
		{
			serializedObject.Update();

			GUILayout.Label("Contents of this file don't matter");

			serializedObject.ApplyModifiedProperties();
		}
	}
}
```

```
using UnityEngine;

namespace TestNamespace
{
	public class TestObject : ScriptableObject
	{
		public float floatValue;
		public int intValue;
	}
}
```

**Comment by jacobdufault** [comment] 2016-07-28 05:56
Thanks for the easy repro instructions.

This will be fixed in the next upload to Access (likely tomorrow).

To fix it now, edit line 10 of `FullInspector2\Core\Editor\fiInspectorOnly_ScriptableObjectEditor.cs`  so it also has `isFallback=true`, ie,
`[CustomEditor(typeof(ScriptableObject), editorForChildClasses: true, isFallback = true)]`

FYI, @karl-  your code should not be assuming that you'll get a `TestEditor` instance since you have `isFallback = true`.

**Closed by jacobdufault** 2016-07-28 05:56 UTC
