### ISSUE TITLE
TextAsset references lost when Unity imports the TextAsset and FullInspector behavior simultaneously

### ISSUE THREAD

**Issue by derubel** [jacobdufault/fullinspector#119] opened 2015-07-06 16:49 UTC
When Unity imports a TextAsset and a prefab containing a FullInspector behavior that references the TextAsset inside of a Serializable class at the same time, the reference to the TextAsset is lost.  For example:

```c#
public class ContainerBehavior : BaseBehavior
{
    public TextAsset textAsset1;
    public GameObject prefab1;

    public Referencer referencer;
}

[Serializable]
public class Referencer
{
    public TextAsset textAsset2;
    public GameObject prefab2;
}
```

If this behavior is placed on a prefab and then the TextAsset (in my case an XML file) and prefab are imported at the same time (e.g. someone else gets both new files from version control), textAsset1 will reference the TextAsset but textAsset2 will not.  For reference, the same action with normal Unity object references (prefab1 & prefab2) works as expected (both variables keep their references).

**Comment by jacobdufault** [comment] 2015-07-07 04:31
Can you send me an email? I'd like to verify that this issue still occurs on the current release, as I'm unable to reproduce it. Repro steps are a little bit tricky here, so I'd like you to verify as well. Thanks!

**Comment by jacobdufault** [comment] 2015-07-08 02:35
Thanks, I think this issue is fixed in the latest build (see the email reply so you can verify).

**Comment by derubel** [comment] 2015-07-08 17:02
Yeah, 2.6.2 fixed it for me.  Thanks much!

**Closed** 2015-07-09 02:15 UTC
